POST http://localhost:17545/api/users
Content-Type: application/json
Accept: application/json

{
  "username": "Yoriichi",
  "password": "untech async",
  "name": "yoriichi"
}


### login user
POST http://localhost:17545/api/users/login
Content-Type: application/json
Accept: application/json

{
  "username": "Yoriichi",
  "password" : "untech async"
}

### Get user
GET http://localhost:17545/api/users/current
Accept: application/json
Authorization: 5e702da3-f5a3-4d2a-98ff-a6cf23bcf8aa

### Update user
PATCH http://localhost:17545/api/users/current
Accept: application/json
Authorization: d120fe7f-9aec-488f-9101-557dd96611f0
Content-Type: application/json

{
  "name": "Tsugikuni"
}


### Logout user
DELETE http://localhost:17545/api/users/current
Accept: application/json
Authorization: 5e702da3-f5a3-4d2a-98ff-a6cf23bcf8aa


### Create Contact
POST http://localhost:17545/api/contact
Content-Type: application/json
Accept: application/json
Authorization: d120fe7f-9aec-488f-9101-557dd96611f0

{
  "first_name": "Vincent",
  "last_name": "Le Teileur",
  "email": "vincent@dev.clom",
  "phone": "1110011"
}

### Update Contact
PUT http://localhost:17545/api/contact/505
Content-Type: application/json
Accept: application/json
Authorization: 202ae79e-585a-4d3c-98d0-9b404b4f8888

{
  "first_name": "Yves",
  "last_name": "Castillon",
  "email": "void_code@dev.com",
  "phone": "0212321"
}

### Search Contact
GET http://localhost:17545/api/contact
Authorization: 5e702da3-f5a3-4d2a-98ff-a6cf23bcf8aa
Accept: application/json


### Remove Contact
DELETE http://localhost:17545/api/contact/506
Authorization: 202ae79e-585a-4d3c-98d0-9b404b4f8888
Accept: application/json

### Create Address
POST http://localhost:17545/api/contact/505/addresses
Authorization: 202ae79e-585a-4d3c-98d0-9b404b4f8888
Accept: application/json
Content-Type: application/json

{
  "street": "Pisangan Baru",
  "city": "Jakarta Timur",
  "province": "DKI Jakarta",
  "country": "Indonesia",
  "postal_code": "13100"
}


### Update Address
PUT http://localhost:17545/api/contact/505/addresses/44
Authorization: 202ae79e-585a-4d3c-98d0-9b404b4f8888
Content-Type: application/json
Accept: application/json

{
  "street": "Saint-Genis-Laval",
  "city": "Lyon",
  "province": "Auvergne-Rhône-Alpes",
  "country": "France",
  "postal_code": "12100"
}


### List contact
GET http://localhost:17545/api/contact/505/addresses
Authorization:  202ae79e-585a-4d3c-98d0-9b404b4f8888
Accept: application/json


### Remove Contact
DELETE http://localhost:17545/api/contact/505/addresses/47
Authorization:  202ae79e-585a-4d3c-98d0-9b404b4f8888
Accept: application/json


