POST http://localhost:3000/api/users
Content-Type: application/json
Accept: application/json

{
  "username": "Vermilion",
  "password": "atmin",
  "name": "Jieyra"
}


### login user
POST http://localhost:3000/api/users/login
Content-Type: application/json
Accept: application/json

{
  "username": "AsyncFnc",
  "password" : "rahasia"
}

### Get user
GET http://localhost:3000/api/users/current
Accept: application/json
Authorization: 0fc87baf-9a2d-42f5-bc87-dd482ccb9e41

### Update user
PATCH http://localhost:3000/api/users/current
Accept: application/json
Authorization: 0fc87baf-9a2d-42f5-bc87-dd482ccb9e41
Content-Type: application/json

{
  "name": "Castillon"
}


### Logout user
DELETE http://localhost:3000/api/users/current
Accept: application/json
Authorization:  545d049d-53d3-4b96-be2e-af7012d9858b


### Create Contact
POST http://localhost:3000/api/contact
Content-Type: application/json
Accept: application/json
Authorization: 202ae79e-585a-4d3c-98d0-9b404b4f8888

{
  "first_name": "Vincent",
  "last_name": "Le Teileur",
  "email": "vincent@dev.clom",
  "phone": "1110011"
}

### Update Contact
PUT http://localhost:3000/api/contact/505
Content-Type: application/json
Accept: application/json
Authorization: 202ae79e-585a-4d3c-98d0-9b404b4f8888

{
  "first_name": "Yves",
  "last_name": "Castillon",
  "email": "void_code@dev.com",
  "phone": "0212321"
}

### Search Contact
GET http://localhost:3000/api/contact
Authorization: 202ae79e-585a-4d3c-98d0-9b404b4f8888
Accept: application/json


### Remove Contact
DELETE http://localhost:3000/api/contact/506
Authorization: 202ae79e-585a-4d3c-98d0-9b404b4f8888
Accept: application/json

### Create Address
POST http://localhost:3000/api/contact/505/addresses
Authorization: 202ae79e-585a-4d3c-98d0-9b404b4f8888
Accept: application/json
Content-Type: application/json

{
  "street": "Pisangan Baru",
  "city": "Jakarta Timur",
  "province": "DKI Jakarta",
  "country": "Indonesia",
  "postal_code": "13100"
}


### Update Address
PUT http://localhost:3000/api/contact/505/addresses/44
Authorization: 202ae79e-585a-4d3c-98d0-9b404b4f8888
Content-Type: application/json
Accept: application/json

{
  "street": "Saint-Genis-Laval",
  "city": "Lyon",
  "province": "Auvergne-Rhône-Alpes",
  "country": "France",
  "postal_code": "12100"
}


### List contact
GET http://localhost:3000/api/contact/505/addresses
Authorization:  202ae79e-585a-4d3c-98d0-9b404b4f8888
Accept: application/json


### Remove Contact
DELETE http://localhost:3000/api/contact/505/addresses/47
Authorization:  202ae79e-585a-4d3c-98d0-9b404b4f8888
Accept: application/json


